# Generated by Django 5.1.4 on 2025-07-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='msg',
            new_name='message',
        ),
    ]
